spring:
  jpa:
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: none # h2 treats NUMBER as DECIMAL, but the validation expects NUMBER and fails

  datasource:
    #url: jdbc:h2:tcp://localhost:9092/visco-overviews;MODE=Oracle
    url: jdbc:h2:mem:visco-overviews;Mode=Oracle;DB_CLOSE_DELAY=-1 # ;TRACE_LEVEL_SYSTEM_OUT=3
    # 'Mode=Oracle' only gives very limited compatibility, see http://www.h2database.com/html/features.html#compatibility
    username: sa
    password: sa

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

  sql:
    init:
      platform: h2
